- .github/workflows/equinix_k8s_flow.yml
Starting the Performance work. Need prometheus so we can measure the overhead of components.
> Adding Prom

- .github/workflows/equinix_k8s_flow.yml
node-density will create idle pods on nodes which have `worker=` role.
> Adding First Perf test

- .github/workflows/equinix_k8s_flow.yml
Need to wait for monitoring replicas to be up and running
fixes #19
> Wait for monitoring pods to be running

- .github/workflows/equinix_k8s_flow.yml
The statefulset needs to be created before we can wait on it.
> Need to wait on statefulset

- .github/workflows/equinix_metal_kepler_action_flow.yml
try to run kepler-action on GHA self hosted instance on BM server created by this Repo.
> integrate with kepler action as BM self host runner provider

- .github/workflows/equinix_metal_kepler_action_flow.yml
> fix bug for kepler-action integration

- .github/workflows/equinix_metal_kepler_action_flow.yml
switch to kepler action main as following action of #27
> switch to kepler action main

- .github/workflows/equinix_k8s_kepler_action.yml
- .github/workflows/equinix_metal_kepler_action_flow.yml
with https://github.com/sustainable-computing-io/kepler-action/pull/126 kepler-action supports for existing k8s cluster by Equinix, use this PR for integration.
> try to integrate with kepler action

- .github/workflows/equinix_k8s_trainer.yml
Integrated Model Server Tekton Trainer with Kepler and Prometheus. 
Note that I am unable to run this from my branch. It does not show up as a workflow.
> Integrate Model Trainer

- .github/workflows/equinix_k8s_trainer.yml
- util/inspect.yml
- util/wait_for_pipelineruns.sh
Fixed a few issues with the trainer. More changes have to be made however for trainer to start functioning. This PR however will remove Model Training workflow from being called during pull requests.
> feat(trainer): Update Trainer

- .github/workflows/equinix_metal_flow_model_server_test.yml
- ansible/inventory.yml
- ansible/kepler_playbook.yml
- ansible/model_server_playbook.yml
Implemented Model Server Ansible Playbook to deploy model server on my-vm.
> feat(metal-ci): Add Model Server Ansible Playbook

- .github/workflows/equinix_metal_flow_model_server_test.yml
Renamed Model Server Workflow.
> Rename Model Server Workflow

- .github/workflows/equinix_metal_flow_model_server_test.yml
Added a placeholder workflow for model server in order to test the actual workflow in addModelServerCI branch.
> fix(model_server_test): Add placeholder for model server test to main

- ansible/model_server_playbook.yml
Moved Enable and Start Docker Service Task to the beginning.
> fix(model server integration): Add Enable and Start Docker Service

- ansible/model_server_playbook.yml
Switched to Podman Docker (enables Docker Compose) from Docker due to compatability.
> fix(model_integration): Switch to Podman from Docker

- ansible/kepler_playbook.yml
- ansible/model_server_playbook.yml
Included VM Kepler Docker Compose to confirm Model Server and Estimator integration.
> feat(model_server_e2e): Include VM Kepler Docker Compose

- ansible/model_server_playbook.yml
Add indent to seconds command in ansible.builtin.pause.
> fix(model_server_e2e): indent seconds

- .github/workflows/stress_test_regression_check.yml
- util/stress_regression_check.py
- util/validation_regression_check.py
some dup code are here, will refactor after initial test
> add validation regression checker

- util/validation_regression_check.py
> bot: ignore idle mode validation regression

- .github/workflows/equinix_metal_flow.yml
- ansible/inventory.yml
- ansible/kepler_playbook.yml
- ansible/model_server_playbook.yml
Added Model Server to Metal CI Validator.
> feat(model_server): Incorporate Model Server

- .github/workflows/equinix_metal_flow_model_server_test.yml
Removed daily schedule and commiting of reports for this workflow as it is only to be used for testing.
> chore(model_server): Remove Schedule and Git Push for Testing

- .github/workflows/equinix_k8s_provision.yml
this is to provision k8s cluster, without kepler. So people can use it to test Kepler and model server integration.
> chore: add a k8s provisioning flow

- .github/workflows/equinix_metal_model_server_action_flow.yml
Changed workflow time from 6pm to 11pm to avoid conflict with other workflows.
> fix(model_server): change workflow time to 11pm UTC

- ansible/inventory.yml
- ansible/model_server_playbook.yml
Added model_server_enable and model_server_url ansible vars which are customizable. Set model_server_enable to false as we use static models.
> fix(model_server): add model_server ansible vars

- ansible/inventory.yml
- ansible/model_server_playbook.yml
Updated Model Server Version to new 0.7.11-2
> chore(model_server): Update Model Server Version to 0.7.11-2

- .github/workflows/equinix_metal_e2e.yml
> feat(model_e2e): Added Model e2e

- ansible/node_exporter_playbook.yml
> fix node_exporter_playbook.yml

- .github/workflows/equinix_metal_flow_model_server_test.yml
- .github/workflows/equinix_metal_model_server_action_flow.yml
This commit updates the remaining workflows to properly reference the reports and artifacts from the respective directories.
> chore(ci): Update workflows for consistent artifact handling

- .github/workflows/equinix_metal_e2e.yml
- .github/workflows/equinix_metal_e2e_isolated_servers.yml
- docs/train-validate-e2e/2024-09-04_14-45-33/AbsPower/BPFOnly/ExponentialRegressionTrainer/report-v0.7.11-196-g6a76bc35.md
- docs/train-validate-e2e/2024-09-04_14-45-33/AbsPower/BPFOnly/LogarithmicRegressionTrainer/report-v0.7.11-196-g6a76bc35.md
- docs/train-validate-e2e/2024-09-04_14-45-33/AbsPower/BPFOnly/SGDRegressorTrainer/report-v0.7.11-196-g6a76bc35.md
Pushed Validation Results for target models to repo.
> chore(push_validations): Push Validation Results to Github Repo

- .github/workflows/equinix_metal_e2e.yml
- .github/workflows/equinix_metal_e2e_isolated_servers.yml
- .github/workflows/equinix_metal_flow.yml
- .github/workflows/equinix_metal_flow_model_server_test.yml
- .github/workflows/equinix_metal_model_server_action_flow.yml
- README.md
Renamed workflows to be more descriptive and included Workflow descriptions in README.
> chore(rename_workflows): Renamed workflows to be more descriptive

- .github/workflows/equinix_metal_e2e.yml
- .github/workflows/equinix_metal_e2e_isolated_servers.yml
Instead of only moving report, move all relevant data in validation to github repo.
> chore(push_validations): Move all Validation Data to Repo

- docs/analytics/README.md
- docs/analytics/pyproject.toml
- docs/analytics/src/kepler_analytics/__about__.py
- docs/analytics/src/kepler_analytics/__init__.py
- docs/analytics/src/kepler_analytics/__main__.py
- docs/analytics/src/kepler_analytics/cli/__init__.py
- docs/analytics/src/kepler_analytics/cli/analytics.py
This commit adds a hatch based pyproject for running jupyter notebooks locally. It also ports the kepler_analytics.py as `kepler-analytics` CLI that has `run` command.
> feat(pyproject): for analytics

- .github/workflows/equinix_metal_flow.yml
- ansible/inventory.ini
- ansible/inventory.yml
- ansible/metal_prometheus.yml
- ansible/metrics_playbook.yml
- ansible/node_exporter_playbook.yml
- ansible/roles/node-exporter/defaults/main.yml
- ansible/roles/node-exporter/handlers/main.yml
- ansible/roles/node-exporter/tasks/config.yml
- ansible/roles/node-exporter/tasks/install.yml
- ansible/roles/node-exporter/tasks/main.yml
- ansible/roles/node-exporter/tasks/run.yml
- ansible/roles/node-exporter/templates/node_exporter.service.j2
Added playbook to install node exporter
sample run: https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/10723983767
> chore: Add playbook to install node-exporter

- .github/workflows/equinix_k8s_flow_churncheck.yml
changed commands to change working directory
> changed commands

- ansible/roles/kvm_vm/defaults/main.yml
This needs the runner to set isolated cores first
https://github.com/equinix-labs/metal-runner-action/issues/13
> chore: use isolated cpu for the vm

- .github/workflows/equinix_k8s_flow_churncheck.yml
- docs/kepler-stress-test-baselined-metrics-churn.md
- docs/kepler-stress-test-baselined-metrics.md
Added new docs to test indexing of new metrics
> indexing metrics

- ansible/inventory.yml
- ansible/model_trainer_playbook.yml
Added hatch run to trainer playbook which resolved -1 node index error and other errors produced by incorrect environment setup.
> fix(node_config): Add hatch run to trainer

- README.md
This commit updates the README to include the steps for using Prometheus snapshot for debugging the validation runs
> docs: add steps for using Prometheus Snapshot

- .github/workflows/equinix_metal_model_server_action_flow.yml
Added git checkout before playbooks to resolve git error.
> fix(model_server): Resolve git error

- .github/dependabot.yml
add dependency bot setting to bump up github actions version.
> [CI] add Dependency Bot settings

- .github/workflows/equinix_k8s_kepler_action.yml
ref to #287 , our CI may fail and the ansible steps log is redirected to a specific file, add an error handle step to fetch the error msg.
> add error handle for action steps

- .github/actions/train-action/action.yml
- .github/workflows/equinix_metal_e2e.yml
- .github/workflows/equinix_metal_e2e_isolated_servers.yml
- .github/workflows/equinix_metal_trainer.yml
- ansible/model_trainer_playbook.yml
Added features to upload Training Log Results as artifacts and to origin repository via dependabot. These logs contain information on the success of training as well as MAPE, MAE test results of trained models.
> feat(train_logs): Upload Training Logs

- .github/actions/train-action/action.yml
- .github/workflows/equinix_metal_e2e.yml
- .github/workflows/equinix_metal_e2e_isolated_servers.yml
- .github/workflows/equinix_metal_trainer.yml
- ansible/host_vars/localhost.yml
- ansible/model_server_restart.yml
- ansible/model_trainer_playbook.yml
- ansible/tasks/validate_model_server.yml
Added feature to train models with vm metrics and validate them. Only e2e will be updated with the vm metrics. e2e_isolated_servers will remain baremetal training.
> feat(vm_metrics): Add vm metrics training process

- ansible/model_server_restart.yml
- ansible/model_trainer_playbook.yml
Switched model server training branch from vm-train to main repo. Removed excess logs as well.
> fix(switch_to_main): Switched model server branch to main repo

- .github/workflows/aws_ami_centos9_nvidia_driver.yml
passed here https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/11745576631/job/32723320521
> Creating AMI with NVIDIA driver

- .github/actions/kepler_model_server/action.yml
- .github/actions/kube_config/action.yml
- .github/actions/setup_kepler/action.yml
- .github/workflows/equinix_k8s_flow.yml
- .github/workflows/equinix_k8s_flow_churncheck.yml
- .github/workflows/equinix_k8s_kepler_action.yml
- .github/workflows/equinix_k8s_provision.yml
- .github/workflows/equinix_k8s_trainer.yml
- .github/workflows/pr.yml
ref https://github.com/sustainable-computing-io/kepler-metal-ci/pull/313#issuecomment-2467317727 try to set up a minimum scope for pipeline jobs. To protect pipeline code logic works as much as possible.
In this PR, refactor code with reusable pipeline.
the reusable part is tested with GHA based runner to avoid resource constraint.
at the meanwhile, with this refactor, all code in one place, following pipeline as code, and been tested with a free k8s cluster to make sure the code is runnable.
> [Feat][Chore] Pr level protect

- .github/workflows/create_equinix_k8s_cluster.yml
- .github/workflows/equinix_k8s_flow.yml
- .github/workflows/equinix_k8s_flow_churncheck.yml
- .github/workflows/equinix_k8s_kepler_action.yml
- .github/workflows/equinix_k8s_provision.yml
- .github/workflows/equinix_k8s_trainer.yml
It looks like we have some duplicate code, so I just start to make code reusable by ref @KaiyiLiu1234 's previous code change.
btw, what's termination_time meaning? in most case the value is 1 but in this Github action the value is 6.
https://github.com/sustainable-computing-io/kepler-metal-ci/blob/main/.github/workflows/equinix_k8s_flow_churncheck.yml#L83
> [Nit] code refactor

- .github/actions/train-action/action.yml
- .github/workflows/aws_metal_e2e.yml
- .github/workflows/equinix_metal_e2e.yml
- .github/workflows/equinix_metal_trainer.yml
- ansible/tasks/validate_model_server.yml
This PR enables trainer workflows to also upload the prometheus snapshot to use to view the training and validation data being used. A checker to determine that prometheus and VM metrics are available before training is also included.
> feat(prometheus_snapshot): Upload prometheus snapshot for trainer workflows

- .github/workflows/aws_metal_e2e.yml
- .github/workflows/equinix_metal_e2e.yml
Add train logs to repo. We need this to debug some issues with the aws and equinix workflow when power is at 0. If they are too large, I will upload them as artifacts.
> feat(upload-train-logs): Upload train logs to repo

- ansible/model_trainer_playbook.yml
Replace .txt extension with .log extention to train logs.
> fix(add-train-logs) Add .log extension to train logs

- .github/workflows/aws_metal_e2e.yml
- .github/workflows/equinix_metal_e2e_isolated_servers.yml
Merged duplicate env keyword call in train and validate workflows.
> fix(duplicate-env): Remove duplicate env keyword

- .github/workflows/equinix_metal_flow.yml
- .github/workflows/equinix_metal_model_server_action_flow.yml
- .github/workflows/validator_compose.yml
as 1st step, I suppose we should start to use artifacts to keep the result. ref https://github.com/sustainable-computing-io/kepler-metal-ci/issues/339#issuecomment-2487590908
> [CI]: using artifacts to keep result, a part of #339

- .github/workflows/pr.yml
- ansible/roles/kepler_systemd/tasks/metal.yml
- ansible/roles/kepler_systemd/tasks/vm.yml
attempt to use config-dir to fix config folder check issue.
slack discussion at https://cloud-native.slack.com/archives/C05QK3KN3HT/p1732922326013359
> [fix]: attempt to use config-dir to fix config folder check issue

- .github/workflows/equinix_metal_model_server_action_flow.yml
fix #331
add missing env for estimator service.
> [fix]: add missing env for estimator service
