ansible/metrics_playbook.yml

This commit sets prometheus scrape-config to 3s so that the scrapes aren't too far apart.

fix: 0 metrics found error do to large scrape-config

---

docs/analytics/kepler_analytics.py

chore: when rendering the comparison chart, reset the timestamp so that charts are not stretched

---

ansible/kepler_openmetrics.yml
ansible/kepler_playbook.yml

OpenMetrics can be used to verify other configurations. It is not used in validation. It is also found pm is busy during stress test and causes validation test hard to track.

chore: decouple kepler and open metrics

---

.github/workflows/equinix_metal_flow.yml

Not all processors support reading of all (`core, uncore, dram, package`) power domains. Sometimes dram is missing, other times even core is missing. This PR adds a step which tries to capture the available domains. Kepler power metrics depend on availability of these domains.

chore(rapl): Add a step to capture RAPL power domain availability

---

.github/workflows/equinix_metal_flow.yml

This keeps reports and artifacts in its own dir and avoids moving report outside the `validator-<tag>` directory so that md files can embed relative to its location.
Requires: https://github.com/sustainable-computing-io/kepler/pull/1755

chore(metal/flow): keep reports and artifacts its own dir

---

.github/workflows/equinix_metal_flow.yml
ansible/roles/node-exporter/templates/node_exporter.service.j2

With all default collectors enabled, node-exporter produces a lot of metrics, and prometheus can timeout scraping node-exporter.
This PR :
- Disable default collectors
- Only enable collectors `cpu, cpufreq, perf, rapl, meminfo`

chore: enable selected collectors in node-exporter

---

.github/workflows/clean_equinix_runner.yml
README.md

This commit updates metal delete action in our CI to use the forked version maintained under sustainable-computing-io organization.

chore(ci): update metal delete action to use sustainable-computing-io fork

---

ansible/group_vars/all.yml
ansible/host_vars/localhost.yml
ansible/host_vars/my-vm.yml
ansible/inventory.ini
ansible/inventory.yml

This commit restructures the Ansible variables by:
- Moving host-specific variables to the `host_vars` directory.
- Moving shared variables to the `group_vars` directory for better separation and reusability.
Additionally:
- The `inventory.ini` file has been deleted, as it was not being used.
- The `inventory.yml` file has been updated to reflect these changes.

chore(ansible): refactor variable structure by moving host-specific and shared vars

---

.github/workflows/equinix_metal_flow.yml
.github/workflows/equinix_metal_model_server_action_flow.yml
ansible/metrics_playbook.yml

This commit introduces support for capturing Prometheus Snapshot to assist with debugging and to provide a clearer understanding of Prometheus'state and the observed results
Key changes:
- Adds `prometheus_config_flags_extra` variable to prometheus role,
enabling `web.enable-admin-api` and `web.enable-lifecycle` flags,
which are required to take snapshot
- Updates the existing `equinix_metal_model_server_action_flow.yml`
and `equinix_metal_flow.yml` workflows to capture the snapshot
after the validator completes, storing it in the
`docs/validation/<date>/validator-<kepler_tag>/prometheus-snapshot/`
directory
Addresses: #264

feat: Add support for capturing Prometheus snapshot

---

.github/workflows/equinix_k8s_flow.yml
.github/workflows/equinix_k8s_flow_churncheck.yml
.github/workflows/equinix_k8s_kepler_action.yml
.github/workflows/equinix_k8s_provision.yml
.github/workflows/equinix_k8s_trainer.yml

a hot fix for actions/upload-artifact and actions/download-artifact
ref 
- https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/11146969903/job/30980143377?pr=284#step:1:27
- https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

[CI] Hot fix for actions/upload-artifact and actions/download-artifact

---

.github/workflows/create_equinix_runner.yml

This commit updates the equinix metal-runner-action to use `main` which includes the latest changes to the action

chore(ci): use latest equinix metal-runner-action

---

.github/workflows/equinix_metal_flow.yml
.github/workflows/equinix_metal_model_server_action_flow.yml

This update modifies the validator directory structure by appending a timestamp to the directory name. This change ensure that multiple validator results can be stored within the same date directory
Address: #230

feat: add timestamp to validator directory

---

ansible/model_server_playbook.yml
ansible/roles/kepler_systemd/tasks/vm.yml

Following Oct 15 community meeting discussion, we disable idle power exposure during training and validation

chore: not expose estimated idle power

---

.github/workflows/equinix_metal_flow.yml
.github/workflows/equinix_metal_model_server_action_flow.yml
util/generate_daily_validations.py

Disabled daily validations for validation workflows due to removal of idle metrics. daily validations were breaking the validation workflows because they expect idle metrics. Refractoring must be done in future PRs to remove idle metrics from the graph.

fix(disable_daily_vals): Disable daily validations

---

ansible/model_trainer_playbook.yml

This one depends on https://github.com/sustainable-computing-io/kepler-model-server/pull/533
I ran a test, the BPFOnly SGD accuracy is much improved
```bash
14             BPFOnly               SGDRegressorTrainer_0  14.32    7.68
14             BPFOnly               SGDRegressorTrainer_0  13.07    10.18
```
The result in previous training in https://github.com/sustainable-computing-io/kepler-metal-ci/blob/main/docs/train-validate-e2e/2024-10-24_11-19-37/train_logs.txt:
```
BPFOnly               SGDRegressorTrainer_0  0.20   123.86
BPFOnly               SGDRegressorTrainer_0  0.22   314.52
```

chore: use vm-train option to train models

---

.github/workflows/equinix_metal_e2e.yml
ansible/host_vars/my-vm.yml
ansible/kepler_validator.yml
ansible/metrics_playbook.yml
ansible/model_server_restart.yml

This is the prometheus chart during training (9:52 to 10:04), using the upstream models, and validation that uses trained models (10:30 to 10:34). As observed, the trained models show good alignment between the VM and metal jobs
The validation results are:
```
"Run validations",
"node-rapl - kepler-package",
"  - node-rapl  :  sum( rate( node_rapl_package_joules_total[20s] ) )",
"  - kepler-package  :  sum( rate( kepler_node_package_joules_total{ job=\"metal\", }[20s] ) )",
"\t MSE : 4.42",
"\t MAPE: 3.13 %",
"\t MAE : 1.65",
"",
"platform - absolute",
"  - metal  :  sum( rate( kepler_vm_platform_joules_total{ job=\"metal\", vm_id=~\".*my-vm\", }[20s] ) )",
"  - vm  :  sum( rate( kepler_node_platform_joules_total{ job=\"vm\", }[20s] ) )",
"\t MSE : 7574.30",
"\t MAPE: 75.44 %",
"\t MAE : …
```

chore: use the latest model server image tag

---

ansible/host_vars/my-vm.yml
ansible/model_server_playbook.yml

Rather than use python3.10 which is a hard dependency, we should use model-server's pyproject.toml hatch commands (model-server and estimator) to deploy the Model Server services. Additionally, we should use stable version 0.7.12 which should contain the fix for the estimator.

chore(model-server): Use hatch to deploy Model Server

---

.github/workflows/equinix_metal_e2e.yml

Added AbsPower/BPFOnly/PolynomialRegressionTrainer,AbsPower/BPFOnly/XgboostFitTrainer to the list of target models to validate. Note this will add an additional hour to the training and validation e2e workflow.

chore(validate_model_defaults): Added Polynomial and Xgboost to default list of target models

---

.github/workflows/aws_metal_e2e.yml
.github/workflows/equinix_metal_e2e.yml

Destination filepath was corrected to include github workspace filepath.

fix(upload-train-logs): Add correct destination filepath for log upload

---

ansible/roles/kepler_systemd/defaults/main.yml
ansible/roles/kepler_systemd/tasks/metal.yml
ansible/roles/kepler_systemd/tasks/vm.yml
ansible/roles/kepler_systemd/vars/main.yml

This commit introduces a dedicated configuration file for Kepler when
deployed using systemd. It ensures separate configs for VM and metal deployments,
enhancing modularity and maintainability.
Key changes:
- Kepler configs are now defined in a separate config file(`/etc/kepler/kepler.config/`)
instead of as environment variables in the systemd service file.
- This approach simplifies systemd service management and ensures Kepler
reads config from the default file location

feat(ansible): add Kepler config file support

---

.github/actions/setup_kepler/action.yml
.github/workflows/pr.yml

I suppose fails as kubeconfig location issue happen for https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/12125279560/job/33805564812, here is a PR for test and try to fix it.
add a clean up steps in PR CI, as kubeconfig should download but not keep on the disk.
add additional steps in config kube, which will try best to get kubeconfig file.

[fix]: try with kubeconfig with try best

---

docs/sponsor/call-for-machines.md

Address issue: https://github.com/sustainable-computing-io/kepler/issues/1906?issue=sustainable-computing-io%7Ckepler%7C1916
To list up call for machines document.
@rootfs Could you please help review this PR? 
TODO:

feat: add call for machines
